# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    loader = {
      efi.efiSysMountPoint = "/boot/efi";
    };
    initrd = {
      systemd.enable = true;
      availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
      kernelModules = [];
      supportedFilesystems = ["ntfs" "btrfs"];
    };
    kernelModules = ["kvm-amd"];
    extraModulePackages = [];
    blacklistedKernelModules = ["rt2x00usb" "rt2x00lib"]; # "rt2800usb"
  };
  swapDevices = [
    {
      device = "/swapfile";
      size = 8 * 1024; # Creates an 8GB swap file
    }
  ];
  networking.networkmanager.wifi.powersave = false;
  boot.extraModprobeConfig = ''
    options iwlwifi 11n_disable=8
    options iwlwifi swcrypto=1
    options iwlwifi power_save=0
    options iwlwifi power_level=5
    options iwlwifi bt_coex_active=0

    options iwlmvm power_scheme=1
  '';

  hardware.bluetooth.enable = true;
  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
