# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      systemd.enable = true;
      availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
      kernelModules = [];
      supportedFilesystems = ["ntfs" "btrfs"];
    };
    kernelModules = ["kvm-amd"];
    extraModulePackages = [];
  };
  swapDevices = [
    {
      device = "/swapfile";
      size = 8 * 1024; # Creates an 8GB swap file
    }
  ];
  # swapDevices = [
  #   {
  #     device = "/swapfile";
  #     size = 8192; # 8GB in MB
  #   }
  # ];
  # # Swapfile configuration (not handled by Disko directly)
  # swapDevices = [
  #   {
  #     device = "/swapfile";
  #     size = 8192;
  #   }
  # ];
  #
  # # Required for Btrfs swapfile
  # boot.specialFileSystems."/swapfile".options = ["nodiratime" "noatime" "noauto" "nofail" "discard"];

  hardware.bluetooth.enable = true;
  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
